### PR TITLE
Fix for run and docs generate on Panoply Redshift

### LINKED ISSUE #1479: Unable to run dbt against Panoply Redshift
## Issue
Unable to run dbt against Panoply redshift

### Issue description
Am testing out the sample model provided by dbt init (my_first_dbt_model.sql)
```
{{ config(materialized='view') }}
select 1 as id
```

Am able to execute `dbt run` in a dev environment (Postgres) and it works fine.
But, when I run it against the Panoply redshift, it throws the error

### Results
I expect it to create a view. But, it throws the below syntax error

```
Encountered an error:
Database Error
  syntax error at or near "with"
  LINE 14:             relkind as kind
```
Attached is the dbt log snippet [dbt.log](https://github.com/fishtown-analytics/dbt/files/3215112/dbt.log)

To make a note, when I copied the query from dbt.log and pasted it into Panoply console, it works fine.

### System information
The output of `dbt --version`:
```
installed version: 0.13.0-a1
   latest version: 0.13.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

```
Note: I had the latest dbt earlier. But, when I posted the same question in slack's support channel, I was recommended to try out fix in https://github.com/kevinsanz93/dbt (and that is why the version appears not up to date)

The operating system am running on is Ubuntu 18.04

The python version you're using (probably the output of `python --version`) 
Python 3.6.7

### Steps to reproduce
`dbt run` against panoply redshift should throw an exception

### PR DESCRIPTION
**Pull request by drewbanin**
Thanks @gautam-ndk for your help in debugging this!

Panoply has two sql rewriting bugs:
 - whitespace before the query begins can cause queries to fail 💀 
 - identifiers named `columns` cause problems; I am quoting or renaming them here

fixes #1479

### CODE REVIEW

File: plugins/redshift/dbt/include/redshift/macros/adapters.sql [hunk 1]
```diff
@@ -80,7 +80,7 @@
           numeric_precision,
           numeric_scale
 
-        from {{ relation.information_schema('columns') }}
```
Comment (cmcarthur) [inline plugins/redshift/dbt/include/redshift/macros/adapters.sql]: how confident are you that this is equivalent

Comment (drewbanin) [reply plugins/redshift/dbt/include/redshift/macros/adapters.sql]: yeah - should be the same thing. This is definitely _not_ equivalent on BQ/Snowflake, but on Redshift, you can only access the `information_schema` for the database that you're connected to. Turns out Redshift ignores capitalization in event quoted identifiers, so all of these are equivalent 🙃 

```
select * from information_schema.columns;
select * from information_schema."columns";
select * from information_schema."COLUMNS";
```

**Comment by wesseljt** [comment]
👏 Thanks guys!
