### PR TITLE
Fix/report compiled node on error

### LINKED ISSUE #1371: RPC Server: return compiled SQL in exceptions when tasks fail during execution
### Feature description
The RPC Server should return the compiled SQL for an `execute` task if the query fails after compilation. The RPC server exception response should include the compiled SQL to help users understand what part of their query failed.

In the current implementation, users can see the error from the database, but _not_ the query that failed. This makes it difficult to debug errant queries.

### PR DESCRIPTION
**Pull request by beckjake**
Fixes #1371

If a `RuntimeException` has a `node` attribute attached, extract the `injected_sql` (if it exists) and the `raw_sql` from that node and put those values into the error result's `data` attribute with the names `compiled_sql` and `raw_sql`, respectively - this is the same behavior as the current successful result output.

While writing tests for this, I found out that the macro override was broken, and the relevant tests were testing the wrong thing, so I fixed that too.

### CODE REVIEW

File: test/integration/042_sources_test/macros/macro.sql [hunk 1]
```diff
@@ -1,5 +1,5 @@
 {% macro override_me() -%}
-	exceptions.raise_compiler_error('this is a bad macro')
+	{{ exceptions.raise_compiler_error('this is a bad macro') }}
```
Comment (cmcarthur) [inline test/integration/042_sources_test/macros/macro.sql]: ha

Comment (beckjake) [reply test/integration/042_sources_test/macros/macro.sql]: yeah, not my finest moment 😬
