### PR TITLE
When column config says quote, use quotes in SQL to add comments

### LINKED ISSUE #2539: persist_docs should consider column quoting
### Describe the bug
When running a `dbt run`, sql statements to persist docs are failing for columns that must be quoted. dbt does not currently respect the [quote](https://docs.getdbt.com/reference/resource-properties/quote) config when building these DDL statements.

### Steps To Reproduce
```
# dbt_project.yml
name: debug
version: 1.0.0
config-version: 2

models:
  +persist_docs:
    columns: true
```

```
-- models/my_model.sql
select 1 as "2id"
```

```
# models/schema.yml

version: 2

models:
  - name: debug
    columns:
      - name: 2id
        description: "my description"
        quote: true
```

Finally, execute `dbt run` and observe that persisting docs fails.

### Expected behavior
The DDL built by dbt should respect the `quote` config on the `column` declaration for a dbt node

### System information
**Which database are you using dbt with?**
- [x] postgres
- [x] redshift
- [ ] bigquery
- [x] snowflake

This probably does not affect BigQuery since quoting isn't relevant + we use the API

**The output of `dbt --version`:**
```
0.17.0
```

### PR DESCRIPTION
**Pull request by gshank**
resolves #2539

### Description
When 'persist_docs' was turned on, an error occurred if a column had config 'quote: true' because the DDL to add the comment did not quote the column name. This fix passes the column quote config on to the ColumnInfo object and checks that config when constructing the SQL to add a comment.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by beckjake** [comment]
@cla-bot check

File: plugins/postgres/dbt/include/postgres/macros/adapters.sql [hunk 1]
```diff
@@ -155,6 +155,6 @@
   {% for column_name in column_dict %}
     {% set comment = column_dict[column_name]['description'] %}
     {% set escaped_comment = postgres_escape_comment(comment) %}
-    comment on column {{ relation }}.{{ column_name }} is {{ escaped_comment }};
+    comment on column {{ relation }}.{{ adapter.quote(column_name) if column_dict[column_name]['quote'] == True else column_name }} is {{ escaped_comment }};
```
Comment (beckjake) [inline plugins/postgres/dbt/include/postgres/macros/adapters.sql:158]:
```suggestion
    comment on column {{ relation }}.{{ adapter.quote(column_name) if column_dict[column_name]['quote'] else column_name }} is {{ escaped_comment }};
```

`True` is the only truthy value we need to care about for `quote`, so no need to actually compare it to True.

File: test/integration/060_persist_docs_tests/models/quote_model.sql [hunk 2]
```diff
@@ -0,0 +1 @@
+select 1 as {{ adapter.quote("test2id") }}
```
Comment (beckjake) [inline test/integration/060_persist_docs_tests/models/quote_model.sql:1]: Unfortunately, I don't think this is a very useful test for postgres/redshift. I know columns that start with numbers aren't allowed in bigquery, but this column doesn't require quoting on postgres/redshift and would work fine regardless, so that's not much of a test. Snowflake will have case-sensitivity issues so it's probably still useful there.

I think you'll have to turn this into its own test case. I have done a bit of reading and I actually think that it's fine to exclude Bigquery from this test entirely: since the only things allowed in column names don't require quoting, and unquoted column names are case-preserving, quoting columns on Bigquery seems to be totally meaningless (identifiers are less restrictive, so quoting matters there: hyphens come to mind).

**Review by beckjake — COMMENTED** [review]
Once the release version/changelog nonsense is all sorted, this looks good to me! Love to see those snowflake tests behaving like everyone else too (comments in the catalog), so thanks for getting that in there!

**Review by beckjake — APPROVED** [review]

**Review by jtcohen6 — APPROVED** [review]
LGTM, nice work on this!

Thinking beyond this PR: I wonder if there's a good way to abstract over
```
{{ adapter.quote(column_name) if column_dict[column_name]['quote'] else column_name }}
```
Since that's effectively what we'd need to fix #2468 as well.

**Comment by beckjake** [comment]
it does seem like a macro or adapter method that we could write, doesn't it?
```jinja
{% macro quoted_column(column_dict, column_name) %}
  {% set result = column_name %}
  {% if column_dict[column_name]['quote'] %}
    {% set result = adapter.quote(column_name) %}
  {% endif %}
  {% do return(result) %}
{% endmacro %}
```
