### PR TITLE
dbt test --store-failures

### LINKED ISSUE #517: compiled dbt test output could be more helpful
Consider compiling a simple `select` statement (w/ a `limit`) that can be directly run to find test failures. Right now, you need to change a `select count(*)` to `select *` and sometimes remove groups, add limits, etc.

### LINKED ISSUE #903: Record failing rows for tests into an auditable table
### Feature description
dbt should record rows that fail schema or data tests into tables, to be used for auditing. There are two general ways this could work:

1. insert into an `errors` table with a schema like:
 - run started at
 - invocation id
 - test name
 - failing row primary key / json

2. Create a table for each test failure in a scratch schema, matching the schema of the test query that failed

The baked-in schema tests will need to be rewritten to provide debuggable information in these tables.

This should probably be an opt-in feature for tests. It could be configured either in `schema.yml`, though it would also be good to configure whole swaths of tests at once.

### Who will this benefit?
dbt users could use this table to quickly determine why their tests failed. At present, it's surprisingly difficult to debug a failed test.

### LINKED ISSUE #2593: Storing test results in the database
### Describe the feature

dbt testing is powerful; being notified when a test fails can be life-saving; debugging those failed tests could be easier!

There are two long-lived issues related to this subject ([#517](https://github.com/fishtown-analytics/dbt/issues/517) and [#903](https://github.com/fishtown-analytics/dbt/issues/903)), and dozens of valuable comments on both. After discussing with several colleagues and a few community members, we've arrived at an approach I feel good about.

The goal here isn't to build a dimensional model of historical data surrounding dbt invocations. I think we can and should build out capacity for those longitudinal analyses, but it should be powered by dbt artifacts (manifest and run results) rather than adding records to database tables (a la [logging](https://github.com/fishtown-analytics/dbt-event-logging) package).

Rather, the goal is to add tooling that can be of immediate benefit to dbt developers, for whom debugging tests is a slog that's harder than it needs to be. We want to provide the post-test investigator with a high-level overview of `dbt test` statuses, and the errant records from any failing tests, within a query or two.

A lot of this work is going to build on top of v2 schema tests ([#1173](https://github.com/fishtown-analytics/dbt/issues/1173)) and data tests ([#2274](https://github.com/fishtown-analytics/dbt/issues/2274)), both of which are on the [1.0.0 docket](https://github.com/fishtown-analytics/dbt/labels/1.0.0). So while this feature is not coming in the next month or two, it is firmly on the roadmap.

## Spec: v2 schema tests

To get where we want to go, we need to talk a little about our planned changes to schema tests.

Let's imagine a modified version of the current `not_null` schema test. Several small things are different, the most significant of which is that the test returns a set of records instead of just `count(*)`, similar to how data tests work today:

```sql
{% test not_null(model, column_name) %}

    {% set name = 'not_null__' ~ model.name ~ '__' ~ column_name %}

    {% set description %} Assert that {{ column_name }} is never null in {{ model }} {% endset %}

    {% set fail_msg %} Found {{ result }} null values of {{ model }}.{{ column_name }} {% endset %}
        
    {{ config(name=name, description=description, fail_msg=fail_msg) }}
    
    select * from {{ model }}
    where {{ column_name }} is null

{% endmacro %}
```

Let's say we have two `not_null` tests defined in our project, in a file called `resources.yml`:

```yaml
version: 2

models:
  - name: customers
    colums:
      - name: id
        tests:
          - not_null

  - name: orders
    columns:
      - name: order_status
        tests:
          - not_null
```

The standard way of executing these tests looks like compiling and running some queries, and storing the compiled version of those queries in the `target` directory:

```sql
-- compiled SQL stored in target/compiled/models/resources.yml/schema_test/not_null__customers__id.sql`

select count(*) from (
    select * from dev_jcohen.customers
    where id is null
) validation_errors
;

-- compiled SQL stored in target/compiled/models/resources.yml/schema_test/not_null__orders__order_status.sql`

select count(*) from (
    select * from dev_jcohen.orders
    where order_status is null
) validation_errors
;
```

After running, dbt returns any failures as log output to the CLI:

```bash
12:00:01 | 1 of 2 START test not_null__customers__id.........................[RUN]
12:00:02 | 1 of 2 PASS not_null__customers__id.............................. [PASS in 1.00s]
12:00:03 | 2 of 2 START test not_null__orders__order_status................. [RUN]
12:00:04 | 2 of 2 FAIL not_null__orders__order_status....................... [FAIL 7 in 1.00s]

Failure in test not_null__orders__order_status (models/resources.yml)
  Found 7 null values of orders.order_status

  compiled SQL at target/compiled/models/resources.yml/schema_test/not_null__orders__order_status.sql
```

There are many features we imagine unlocking with v2 testing:

- In addition to `warn` severity, more configurable `warn_after` and `error_after` thresholds based on a scalar count or %
- Tagging tests to customize failure notifications

For now, let's focus on storing the results of these tests in the database for easier debugging.

## Spec: storing results

Now let's imagine a new `test` flag:

```bash
$ dbt test --store-results
```

It's unlikely that dbt developers would want to include this flag when iterating on net-new models, but it's quite likely that production or CI test runs would benefit from including it.

When the `--store-results` flag is included, dbt will instead execute tests like so:

```sql
drop schema if exists dev_jcohen__dbt_test_results;
create schema dev_jcohen__dbt_test_results;

create table dev_jcohen__dbt_test_results.not_null__customers__id as (

    -- compiled SQL stored in target/compiled/models/resources.yml/schema_test/not_null__customers__id.sql`

    select * from dev_jcohen.customers
    where id is null

);

create table dev_jcohen__dbt_test_results.not_null__orders__order_status as (

    -- compiled SQL stored in target/compiled/models/resources.yml/schema_test/not_null__orders__order_status.sql`

    select * from dev_jcohen.orders
    where order_status is null
        
);
```

Based on the row count in the query status returned by the database, or by running a quick `count(*)` on each table after creation, dbt will determine whether the test passed or failed and create a summary table of all tests in the invocation. (We'll use a mechanism similar to `dbt seed` to batch inserts and avoid any limits on inserts or query length.)

```sql
create table dev_jcohen__dbt_test_results.summary (
    invocation_id string,
    test_name string,
    status string,
    execution_time timestamp
);

insert into dev_jcohen__dbt_test_results.summary values (
    ('xxxxxxxx-xxxx-0000-0000-xxxxxxxxxxxx', 'not_null__customers__id', 'PASS', '2020-06-25 12:00:01'),
    ('xxxxxxxx-xxxx-0000-0000-xxxxxxxxxxxx', 'not_null__orders__order_status', 'FAIL 7', '2020-06-25 12:00:03')
);
```

And finally log to the CLI:

```bash
12:00:01 | 1 of 2 START test not_null__customers__id.........................[RUN]
12:00:02 | 1 of 2 PASS not_null__customers__id.............................. [PASS in 1.00s]
12:00:03 | 2 of 2 START test not_null__orders__order_status................. [RUN]
12:00:04 | 2 of 2 FAIL not_null__orders__order_status....................... [FAIL 7 in 1.00s]

Failure in test not_null__orders__order_status (models/resources.yml)
  Found 7 null values of orders.order_status
    -------------------------------------------------------------------------
    select * from dev_jcohen__dbt_test_results.not_null__orders__order_status
    -------------------------------------------------------------------------

  compiled SQL at target/compiled/models/resources.yml/schema_test/not_null__orders__order_status.sql
```

### Test definition

dbt will depend entirely on the test block to circumscribe its failures. Each test block query will be responsible for defining:

- Which columns to include in the table of test failures. E.g. `*`, an explicit column list, `dbt_utils.star` or `* (except)` (on BigQuery).
- How many rows to include in the table of test failures, e.g. by adding `limit 500`.

### Audit schema

dbt will store all results in *one* audit schema per `dbt test --store-results` invocation. It will name the schema `{{ target.schema }}__dbt_test_results`.

**Can I name the schema differently? What about tests on models with [custom schemas](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas/)?**

We're going to keep this simple for the first version by storing all tests in one schema with a set name. We envision adding configuration for this later, especially if there is user demand.

**Why does dbt drop and recreate the dbt test audit schema every time?**

`dbt test` is a stateless, idempotent operation; `dbt test --store-results` will be as well. If you run it several times, you will end up with the same artifacts.

**How can I preserve history of *past* test failures?**

The same way you preserve historical data from sources, models, or anything else: [snapshots](https://docs.getdbt.com/docs/building-a-dbt-project/snapshots/) on top of tables in the audit schema, or your own custom run-operation macros to copy or unload that data to external storage.

### Granular control

The `--store-results` flag flips `dbt test` from running a set of queries that performs *only* introspection to a set of queries that create assets in the database.

**Will it be possible to store results for some tests, and not for others?**

In the first version of this, the `--store-results` flag will change the behavior of *all* tests run. Eventually, we envision adding a test config flag (`store_results: false`) that takes precedence over the CLI flag, similar to changes to `--full-refresh` in [0.18.0](https://github.com/fishtown-analytics/dbt/pull/2438).

Until then, you can manage this with multiple commands and node selection:

```bash
dbt test --store-failures --exclude my_massive_model
dbt test --models my_massive_model
```

### PR DESCRIPTION
**Pull request by jtcohen6**
Closes #517
Closes #903
Closes #2593

I also played around with #3265 (print the top 5 failures to stdout, and include in `run_results.json`). This work here is definitely the prerequisite for that, but we should tackle it separately if we decide it's something we want to do.

### Biggest choices
- This is all turned on via a flag, `--store-results`
- Hard-coded default schema for tests: `dbt_test__audit`. Normally, this means the schema is `my_target_schema_dbt_test__audit`; if someone is using `generate_schema_name_for_env`, it will be just `dbt_test__audit`.
    - Note: Because of the work in #3257, users can override this value by setting a `tests: +schema` config in `dbt_project.yml`. So I feel less bad about hard coding it.
- The original proposal in #2593 (and my first cut of this) would have dbt totally blow away the test-audit schema each time. As I said here previously: "This statelessness is actually _desirable_, but we should be immensely careful whenever dbt auto-drops anything." Well, that auto-dropping scared me a bit; now, dbt will drop-if-exists and recreate each test audit _table_, but not the whole schema. It's not an atomic operation, since that's not the point; it's not quite as dramatic as clobbering the whole schema, but it accomplishes our goal.

### Other comments
- I introduced a new node property, `relational()`, which is the same as `refable()` but includes tests IFF `flags.STORE_RESULTS` is turned on. dbt now uses `relational()` to decide which nodes inform the schemas it will create and when it will write the `relation_name` property to the manifest.
- I rewrote the queries defining a few of dbt's builtin generic tests, so that the failing records are more helpful/interesting.
- A table is not dropped if its test passes, i.e. if it contains zero rows. We could add that pretty easily, if it's something we want. Worth considering:
    - What if a test has a pass/fail condition _other_ than `count(*) = 0`? It's possible that a passing test may still have rows in the database that a user would want to inspect
    - Potential bloat to database metadata or block storage. (This isn't additive across invocations, since the test table is dropped and recreated on a subsequent store-failure test, but old/deleted tests would still hang around.)
- There's no centralized "results" table, as proposed in #2593, that contains one row for every test, its status info, and the location of its results table. The question is, do we need this? These days, all of that information is available (and more reliably accessed) from the `run_results.json` artifact.

```
Running with dbt=0.20.0-b1
Found 1 model, 3 tests, 0 snapshots, 0 analyses, 162 macros, 0 operations, 0 seed files, 1 source, 0 exposures

22:23:09 | Concurrency: 8 threads (target='bigquery')
22:23:09 |
22:23:09 | 1 of 3 START test my_custom_bespoke.................................. [RUN]
22:23:09 | 2 of 3 START test not_null_my_model_fun.............................. [RUN]
22:23:09 | 3 of 3 START test unique_my_model_fun................................ [RUN]
22:23:14 | 1 of 3 WARN 1 my_custom_bespoke...................................... [WARN 1 in 4.69s]
22:23:14 | 3 of 3 FAIL 1 unique_my_model_fun.................................... [FAIL 1 in 4.91s]
22:23:14 | 2 of 3 PASS not_null_my_model_fun.................................... [PASS in 4.98s]
22:23:14 |
22:23:14 | Finished running 3 tests in 10.98s.

Completed with 1 error and 1 warning:

Failure in test unique_my_model_fun (models/schema.yml)
  Got 1 result, expected 0.

  compiled SQL at target/run/my_project/models/schema.yml/schema_test/unique_my_model_fun.sql

  See test failures:
  --------------------------------------------------------------------------------
  select * from `dbt-test-env`.`dbt_jcohen___dbt_test_audit`.`unique_my_model_fun`
  --------------------------------------------------------------------------------

Warning in test my_custom_bespoke (tests/my_custom_bespoke.sql)
  Got 1 result, expected 0.

  compiled SQL at target/run/my_project/tests/my_custom_bespoke.sql

  See test failures:
  ------------------------------------------------------------------------------
  select * from `dbt-test-env`.`dbt_jcohen___dbt_test_audit`.`my_custom_bespoke`
  ------------------------------------------------------------------------------
```

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: core/dbt/include/global_project/macros/materializations/test.sql [hunk 1]
```diff
@@ -1,10 +1,46 @@
...
+    {% set old_relation = adapter.get_relation(database=database, schema=schema, identifier=identifier) %}
+    {% set target_relation = api.Relation.create(
+        identifier=identifier, schema=schema, database=database, type='table') -%} %}
+    
+    {% if old_relation %}
+        {% do adapter.drop_relation(old_relation) %}
+    {% endif %}
+    
+    {% call statement(auto_begin=True) %}
+        {{ create_table_as(False, target_relation, sql) }}
```
Comment (drewbanin) [inline core/dbt/include/global_project/macros/materializations/test.sql:17]: this is 🔥

File: core/dbt/node_types.py [hunk 2]
```diff
@@ -49,6 +50,10 @@ def documentable(cls) -> List['NodeType']:
             cls.Exposure
         ]
 
+    @classmethod
+    def relational(cls) -> List['NodeType']:
+        return cls.refable() + ([cls.Test] if flags.STORE_FAILURES else [])
```
Comment (drewbanin) [inline core/dbt/node_types.py:55]: this is.... not ideal... i think. Is there a way that we can push this logic around `flags.STORE_FAILURES` into the caller? Something about changing the behavior of this class method based on a global flag feels pretty fraught

File: core/dbt/parser/schema_test_builders.py [hunk 3]
```diff
@@ -41,14 +41,25 @@ def get_nice_schema_test_name(
...
         label = unique
     else:
         label = hashlib.md5(unique.encode('utf-8')).hexdigest()
 
-    filename = '{}_{}_{}'.format(test_type, test_name, label)
-    name = '{}_{}_{}'.format(test_type, test_name, unique)
+    cutoff = 30
+    test_full_name = '{}_{}'.format(test_type, test_name)
+    if len(test_full_name) <= cutoff:
+        test_prenom = test_full_name
```
Comment (drewbanin) [inline core/dbt/parser/schema_test_builders.py:57]: let's uh... use english.... for variable names :)

File: core/dbt/parser/schema_test_builders.py [hunk 4]
```diff
@@ -231,6 +242,10 @@ def __init__(
         self.compiled_name: str = compiled_name
         self.fqn_name: str = fqn_name
 
+        # use hashed name as alias if too long
+        if compiled_name != fqn_name:
+            self.modifiers['alias'] = compiled_name
```
Comment (drewbanin) [inline core/dbt/parser/schema_test_builders.py:247]: really clever & really cooll!

File: core/dbt/task/runnable.py [hunk 5]
```diff
@@ -524,8 +524,6 @@ def create_schema(relation: BaseRelation) -> None:
 
                 db_schema = (db_lower, schema.lower())
                 if db_schema not in existing_schemas_lowered:
-                    existing_schemas_lowered.add(db_schema)
```
Comment (drewbanin) [inline core/dbt/task/runnable.py:527]: is there a reason why this disappeared?

**Review by drewbanin — COMMENTED** [review]
Some comments dropped inline! Nice work @jtcohen6!

File: core/dbt/task/runnable.py (hunk 5 above)
Comment (jtcohen6) [reply core/dbt/task/runnable.py:527]: nope :) thanks for catching it!

File: core/dbt/parser/schema_test_builders.py (hunk 3 above)
Comment (jtcohen6) [reply core/dbt/parser/schema_test_builders.py]: heh. I decided to reimplement this logic anyway, since it was getting a little confused

File: core/dbt/flags.py [hunk 6]
```diff
@@ -64,11 +65,12 @@ def reset():
     PARTIAL_PARSE = False
     MP_CONTEXT = _get_context()
     USE_COLORS = True
+    STORE_FAILURES = False
```
[the remark this answers is not in the document]
Comment (jtcohen6) [reply core/dbt/flags.py:68]: definitely!

File: core/dbt/node_types.py (hunk 2 above)
Comment (jtcohen6) [reply core/dbt/node_types.py]: Good call. I removed `relational` as a class method and instead implemented this logic as a [`should_store_failures` boolean property of parsed nodes](https://github.com/fishtown-analytics/dbt/pull/3316/files#diff-2865acf9f8c91b43775b17533e2f5ac56f9f6a7bf2fff497e0bc84edaf4af8daR118-R123).

Unfortunately, it's duplicative with logic in the [`should_store_failures()` Jinja macro](https://github.com/fishtown-analytics/dbt/pull/3316/files#diff-4bef0f1be924c18da1624194a38efd20176db97cd0d0bfa6d68f460c7f9e7848R77-R83) used in the `test` materialization, which takes after the `should_full_refresh()` macro. I don't know a good way around this: We need this property accessible in python, for deciding which schemas need to be created as part of the task. I also see merit in making the logic really explicit to users, and allowing them to override it if they'd like. And the places in the codebase where we call Jinja macros from python are... not ideal...

**Comment by jtcohen6** [comment]
Updated:
- Tests accept a `store_failures` config which can be set in all the usual places. This works like `full_refresh`: If set, the config takes precedence over the `--store-failures` flag, so a test either _always_ or _never_ stores its failures. If the config is not set, then the flag takes effect.
- Cleaned up the test aliasing logic.

Known limitations of the current approach:
- Duplicated logic between `should_full_refresh` node property and `should_full_refresh()` Jinja macro (see [comment above](https://github.com/fishtown-analytics/dbt/pull/3316#discussion_r633113784))
- Generic test nodes with too-long names (64+ characters) don't use custom `alias` names or respect the `generate_alias_name()` macro. Instead, they use an alias guaranteed to be both short enough (<64 char) and unique (contains hash). Users _can_ specify `alias`/`schema`/`database` configs for those tests from `dbt_project.yml`, but not in the `.yml` files that specify them. (Should we accept these as `MODIFIER_ARGS`? I'm willing to punt on this for now)

**Review by kwigley — APPROVED** [review]
❤️ this is awesome! looks good to me

**Comment by sphinks** [comment]
Great feature! Any idea when it will be released?

**Comment by jtcohen6** [comment]
@sphinks This will be in v0.20.0, for which we'll have a first release candidate very shortly

**Comment by jranks123** [comment]
Love this, thanks everyone <3

**Comment by jranks123** [comment]
@jtcohen6 This seems to imply it only stores failures - are there any plans to also store non-failures, i.e passes?

**Comment by jtcohen6** [comment]
@jranks123 The test table will store whatever the test query returns. In general, test queries pass when they return zero rows—so the table will still be created, it will just have nothing in it.

In v0.20.0, tests can also have a few new configs—`fail_calc` and `error_if`—such that it's possible to return rows from a test query and still pass, so long as the `fail_calc` does not meet the `error_if` criterion. In that case, `--store-failures` would still cause the test to store the results of its query in a table, even though the test does not ultimately raise an error.
