### PR TITLE
do not double-quote the database name (#2267)

### LINKED ISSUE #2267: The implementation of `default__list_schema` results in double-quoting if databse quoting is true
### Describe the bug
When the quoting config `database: true` is set, and a plugin doesn't override `list_schema`, the `list_schemas` adapter method ends up double-quoting the database name (once in-method, once in the macro).

### Steps To Reproduce
- Create a plugin
- set the default database quoting to true or set it in your project
- get errors about double-quoting the name (`""memory"".INFORMATION_SCHEMA`, in the case of local testing on presto)

### Expected behavior
I expect this to work! We should remove the quoting call from `default__information_schema_name`, at least!

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [X] other (specify: presto 0.16.x)

**The output of `dbt --version`:**
```
dbt==0.16.0
```

**The operating system you're using:**
N/A

**The output of `python --version`:**
N/A

### Additional context
The workaround is to implement `presto__information_schema_name` with a macro that doesn't quote.

### PR DESCRIPTION
**Pull request by beckjake**
resolves #2267 

### Description
I couldn't test this because nothing in dbt actually uses the default implementation (maybe the macro should just go away entirely in 0.17?). But it is what I did to get dbt-presto working, and that seems to work fine.

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: core/dbt/include/global_project/macros/adapters/common.sql [hunk 1]
```diff
@@ -189,7 +189,7 @@
 
 {% macro default__information_schema_name(database) -%}
   {%- if database -%}
-    {{ adapter.quote_as_configured(database, 'database') }}.INFORMATION_SCHEMA
+    database.INFORMATION_SCHEMA
```
Comment (drewbanin) [inline core/dbt/include/global_project/macros/adapters/common.sql:192]: Do we not want `{{ database }}` here?

Comment (beckjake) [reply core/dbt/include/global_project/macros/adapters/common.sql:192]: yes 🤦‍♂ today's lesson is "why we copy+paste instead of re-writing things"
