### PR TITLE
Remove sql_where

### LINKED ISSUE #1351: Remove subquery from incremental models when no sql_where is specified
### Issue description

Redshift Spectrum does not support (some?) nested queries. This includes [a subquery](https://github.com/fishtown-analytics/dbt/blob/v0.12.2/dbt/include/global_project/macros/materializations/incremental/incremental.sql#L61) used in the default incremental materialization.

The generated simple query for my incremental model looks like this:

```sql
  select
      "..." as surrogate_key
    , "etl-date" as etl_date
    , ...
 from spectrum.table
where "etl-date" < to_char(current_date, 'YYYY-MM-DD')
  and "etl_date" > coalesce((select max("etl_date") from "dev"."raw_table"), '0000-00-00')
```

With configuration in `dbt_project.yml` like so:

```yaml
    raw:
      materialized: incremental
      dist: surrogate_key
      sort: ['etl_date']
```

### Results

On runs with `--full-refresh` specified, the model and resulting incremental table is created and selected into as expected. On subsequent runs without `--full-refresh` Redshift complains that the nested query is not allowed. From `logs/dbt.log`:

```
Database Error in model raw_activity (models/raw/raw_activity.sql)
  Spectrum nested query error
  DETAIL:
    -----------------------------------------------
    error:  Spectrum nested query error
    code:      8001
    context:   Expression is not supported by Spectrum.
    query:     0
    location:  nested_query_rewriter.cpp:683
    process:   padbmaster [pid=7955]
```

### Workaround

The nested query in question is on [L61](https://github.com/fishtown-analytics/dbt/blob/v0.12.2/dbt/include/global_project/macros/materializations/incremental/incremental.sql#L61) of the incremental materialization.

```sql
       {% set tmp_table_sql -%}
         {# We are using a subselect instead of a CTE here to allow PostgreSQL to use indexes. -#}
         select * from (
           {{ sql }}
         ) as dbt_incr_sbq

         {% if sql_where %}
         where ({{ sql_where }})
           or ({{ sql_where }}) is null
         {% endif %}
       {%- endset %}
```

The subquery as `dbt_incr_sbq` appears unused in the case where `sql_where` is not present. If `sql_where` is not used, this issue can be worked around by creating a custom materialization that replaces the above with simply:

```sql
       {% set tmp_table_sql -%}
         {{ sql }}
       {%- endset %}
```

### System information

```
(venv) $ dbt --version
installed version: 0.12.2
   latest version: 0.12.2

Up to date!
(venv) $ python --version
Python 2.7.10
(venv) $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D42
```

### PR DESCRIPTION
**Pull request by beckjake**
Fixes #1351

Remove sql_where, solving all `sql_where`-related issues permanently.

### CODE REVIEW

**Comment by cmcarthur** [comment]
Looks ok to me, but @drewbanin should have a look

**Comment by drewbanin** [comment]
This LGTM but now might just be a good time to delete the `sql_where` config altogether, right? It's been deprecated for a few minor releases at this point, and I'd be happy to remove it!

File: core/dbt/include/global_project/macros/materializations/incremental/incremental.sql [hunk 1]
```diff
@@ -58,18 +57,7 @@
...
-             {{ sql }}
-           ) as dbt_incr_sbq
-
-           where ({{ sql_where }})
-             or ({{ sql_where }}) is null
-         {%- else -%}
-           {# If a user is not using sql_where, there's no need for a subselect #}
-           {{ sql }}
-         {%- endif -%}
+         {{ sql }}
```
Comment (drewbanin) [inline core/dbt/include/global_project/macros/materializations/incremental/incremental.sql]: we probably don't need `tmp_table_sql` anymore
