### PR TITLE
prevent locks during full refresh in incremental materialization (fix…

### LINKED ISSUE #2426: Full refresh of incremental tables locks the table during build
### Describe the bug
When running a full refresh of incremental tables, the table is locked when the new table is being built. This locks the table for several minutes in production for large tables.

### Steps To Reproduce
1. Run dbt with full refresh on an incremental table that takes a few minutes to build.
2. Query the table when the full refresh of the table is happening.

### Expected behavior
Expected the original table to be available for querying when the temporary table is being built. The table should be locked only when moving the contents from the temporary table to the original table.

Below is a prototype where only the delete from target table and the insert into the target table are part of the transaction. This locks the table for a much smaller duration:
```
{% call statement(auto_begin=True) %} 
        delete from {{ target_table }};
        insert into {{ target_table }} select * from {{ temporary_table }};
        commit;
 {% endcall %}
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.16.0
   latest version: 0.16.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**
macOS Catalina 10.15.4

**The output of `python --version`:**
Python 3.6.3

### Additional context
When I checked in Slack, I was told this may be a solved problem. However, I do notice a significant difference in query time between the two approaches. Let me know if I am missing something.

### PR DESCRIPTION
**Pull request by drkarthi**
…es #2426)

resolves #2426

### Description

Prevent locks during full refresh in incremental materialization. The code change involves changing the order of operations to reflect the order of operations in a table materialization.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: core/dbt/include/global_project/macros/materializations/incremental/incremental.sql [hunk 1]
```diff
@@ -21,9 +21,17 @@
       {% set backup_relation = existing_relation.incorporate(path={"identifier": backup_identifier}) %}
       {% do adapter.drop_relation(backup_relation) %}
 
+      {% set tmp_identifier = this.identifier ~ "__dbt_tmp" %}
+      {%- set tmp_relation = api.Relation.create(identifier=tmp_identifier,
+                                                          schema=this.schema,
+                                                          database=this.database,
+                                                          type='table') -%}
```
Comment (jtcohen6) [inline core/dbt/include/global_project/macros/materializations/incremental/incremental.sql:28]:
```suggestion
```
We've already got the `tmp_relation` from line 8 above

File: core/dbt/include/global_project/macros/materializations/incremental/incremental.sql [hunk 2]
```diff
@@ -21,9 +21,17 @@
...
+                                                          schema=this.schema,
+                                                          database=this.database,
+                                                          type='table') -%} 
+  
+      {% do run_query(create_table_as(False, tmp_relation, sql)) %}
       {% do adapter.rename_relation(target_relation, backup_relation) %}
-      {% set build_sql = create_table_as(False, target_relation, sql) %}
+      {% do adapter.rename_relation(tmp_relation, target_relation) %}
       {% do to_drop.append(backup_relation) %}
+      {% set build_sql = "select 1;" %}
```
Comment (jtcohen6) [inline core/dbt/include/global_project/macros/materializations/incremental/incremental.sql:34]: It's important that the table creation happens as part of statement called `"main"`, so that the correct adapter response is logged to stdout. In this materialization, that "main" statement is going to run whatever is in `build_sql`.

So I think this should instead be:
```suggestion
	{% set build_sql = create_table_as(False, tmp_relation, sql) %}
	{% set need_swap = true %}
```

Then down below, after the main statement finishes (line 46):
```sql
{% if need_swap %}
    {% do adapter.rename_relation(target_relation, backup_relation) %}
    {% do adapter.rename_relation(tmp_relation, target_relation) %}
{% endif %}
```

**Review by jtcohen6 — COMMENTED** [review]
@drkarthi Thanks for this! I agree with the logic overall. I left a few comments about the specific implementation.

I just switched the base branch to `develop`. Could you pull remote changes and add a changelog note under v0.20.0, and add yourself to the list of contributors?

**Comment by drkarthi** [comment]
@jtcohen6 Thank you for the suggestions! I have made the requested changes. Is this line of code (line 26) still required? 
```
{% do to_drop.append(backup_relation) %}
```
If yes, should we add something to also drop `tmp_relation`?

File: core/dbt/include/global_project/macros/materializations/incremental/incremental.sql [hunk 3]
```diff
@@ -21,8 +21,8 @@
       {% set backup_relation = existing_relation.incorporate(path={"identifier": backup_identifier}) %}
       {% do adapter.drop_relation(backup_relation) %}
 
-      {% do adapter.rename_relation(target_relation, backup_relation) %}
-      {% set build_sql = create_table_as(False, target_relation, sql) %}
+      {% set build_sql = create_table_as(False, tmp_relation, sql) %}
+      {% set need_swap = true %}
```
Comment (jtcohen6) [inline core/dbt/include/global_project/macros/materializations/incremental/incremental.sql:25]: I spent a few minutes comparing the logic here with the logic in the [table materialization](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/include/global_project/macros/materializations/table/table.sql), and the most significant difference is that we're creating a temporary relation here instead of a full (intermediate) relation. To that end, and for greater consistency, I recommend switching out the logic here around `tmp_relation` to instead be for `intermediate_relation`:
```sql
      {#-- Make sure the backup doesn't exist so we don't encounter issues with the rename below #}
      {% set tmp_identifier = model['name'] + '__dbt_tmp' %}
      {% set backup_identifier = existing_relation.identifier ~ "__dbt_backup" %}
      
      {% set backup_relation = existing_relation.incorporate(path={"identifier": backup_identifier}) %}
      {% set intermediate_relation = existing_relation.incorporate(path={"identifier": tmp_identifier}) %}

      {% do adapter.drop_relation(intermediate_relation) %}
      {% do adapter.drop_relation(backup_relation) %}

      {% set build_sql = create_table_as(False, intermediate_relation, sql) %}
```

We can also cut line 8, since at this point it's just adding confusion. (The conditional branch below recreates `tmp_relation` for its own purposes.)

**Review by jtcohen6 — COMMENTED** [review]
Sorry for the delay @drkarthi! I figured out why the integration tests are failing. I've confirmed that with the changes below, the Redshift and Postgres integration tests are successful.

Also: It looks like some of your commits are associated with your GitHub account (@drkarthi), which is all set for the CLA, but other commits are associated with... your GitHub account differently? (`Karthik Ramanthan Dhanalakshmi`). Could you try rebasing/amending your commits to _just_ be your GitHub account email address? I'm hoping that will make the cla-bot happy...

**Comment by drkarthi** [comment]
Thanks for the feedback @jtcohen6! I have made the changes, can you take a look?

**Review by jtcohen6 — APPROVED** [review]
LGTM! Thanks for the contribution @drkarthi
