### PR TITLE
Fix for broken catalog generation on pg/redshift

### LINKED ISSUE #1926: [LMA Regression] redshift get_catalog requires exactly one database
### Describe the bug
Users are seeing the `redshift get_catalog requires exactly one database` error on dbt v0.15.0-rc1 even though they only have a single database specified in their project.

### Steps To Reproduce
Exact reproduction case tbd

### PR DESCRIPTION
**Pull request by drewbanin**
Fixes #1926 

Some recent updates to how the BigQuery information schema is handled changed the corresponding logic for Postgres & Redshift. dbt previously generated multiple `information schema` objects, _one for each pair of schema and database_, then used them to generate a catalog. Since pg/redshift do not allow cross-database queries, this was caught by an internal exception raised by dbt.

This PR pops the schema name out of the information schema Relation before returning it to the schema cache. This is the correct behavior for normal databases - the only one that should work different is BigQuery (which sometimes namespaces the information schema behind a dataset). Both of those changes should be addressed here.

### CODE REVIEW

File: plugins/redshift/dbt/include/redshift/macros/catalog.sql [hunk 1]
```diff
@@ -1,6 +1,7 @@
 
 {% macro redshift__get_base_catalog(information_schemas) -%}
   {%- call statement('base_catalog', fetch_result=True) -%}
+    {{ log(information_schemas, info=true) }}
```
Comment (beckjake) [inline plugins/redshift/dbt/include/redshift/macros/catalog.sql]: I think this shouldn't be here, right?

Comment (drewbanin) [reply plugins/redshift/dbt/include/redshift/macros/catalog.sql]: hahaaaa, thanks :)
