### PR TITLE
(#1717) fix for re-rendering in statement calls

### LINKED ISSUE #1108: log macro fails in pre/post-hook without the select 1 workaround
### Issue description
The `log` macro cause the model evaluation to fail when executed in a model level `pre/post-hook` unless the `select 1` hack is applied.

Here is the relevant snippet from the `dbt_project.yml`

```
# no problem here
on-run-start: "{{ log('project level: pre-hook', True) }}"
on-run-end: "{{ log('project level: post-hook', True) }}"

models:
  # fails
  # pre-hook: "{{ log('models level: pre-hook', True) }}"
  # post-hook: "{{ log('models level: post-hook', True) }}"

  # works
  pre-hook: "{{ log('models level: pre-hook', True) }} select 1"
  post-hook: "{{ log('models level: post-hook', True) }} select 1"
```

### Results
What happened? 

Without the `select 1` workaround I get the following ...
```
Found 3 operations, 91 macros, 0 analyses, 0 seed files, 0 tests, 1 models, 0 archives

project level: pre-hook
16:23:32 | Concurrency: 1 threads (target='prod')
16:23:32 | 
16:23:32 | 1 of 1 START view model experimental.my_first_dbt_model.............. [RUN]
models level: pre-hook
16:23:33 | 1 of 1 ERROR creating view model experimental.my_first_dbt_model..... [ERROR in 0.86s]
project level: post-hook
16:23:33 | 
16:23:33 | Finished running 1 view models in 1.17s.

Completed with 1 errors:

Database Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
  can't execute an empty query
  compiled SQL at target/compiled/my_new_package/example/my_first_dbt_model.sql

Done. PASS=0 ERROR=1 SKIP=0 TOTAL=1
```

What did you expect to happen?

Expected the view to be successfully created with `models level: pre-hook` to be printed before the view creation and `models level: post-hook` after.

### System information
The output of `dbt --version`:
```
installed version: 0.11.1
   latest version: 0.11.1

Up to date!
```

The operating system you're running on: mac sierra

The python version you're using (probably the output of `python --version`) `2.7`

### Steps to reproduce
Add the above `dbt_project.yml` snippet to the sample project autogenerated by `db init` and connect to redshift.

### LINKED ISSUE #1717: Remove the call to render() in the statement macro
### Describe the bug
dbt currently calls [render()](https://github.com/fishtown-analytics/dbt/blob/5c3874a392bfadf07f2c302e195d4d7d791d02e5/core/dbt/include/global_project/macros/core.sql#L3) on already-compiled SQL in statement blocks. This render usually is a no-op -- if the SQL is already compiled, then calling `render()` on it should be a no-op. Sometimes though, compiled code contains valid jinja statements. This can happen if:
- the source code contains a `{% raw %}` block
- a user-supplied configuration is provided which contains uncompiled jinja code ([the culprit in this issue](https://github.com/fishtown-analytics/dbt/issues/1712))

### Steps To Reproduce
Given a model like:
```
-- models/debug.sql

{% raw %}
select '{{ 1 + 1 }}' as debug
{% endraw %}
```

The resulting query that dbt runs should be:
```
create view "analytics"."demo_schema"."debug__dbt_tmp" as (
  select '{{ 1 + 1 }}' as debug
);
```

Instead, it is:
```
create view "analytics"."demo_schema"."debug__dbt_tmp" as (
  select '2' as debug
);
```

### System information
This bug affects all supported database. It was reproduced on 0.14.0 and later, but this particular line of code has existed in dbt for quite a bit longer than that.

### PR DESCRIPTION
**Pull request by drewbanin**
Fixes #1717 
Fixes #1108

This PR removes the call to `render()` in statement blocks. For most applications of dbt, this shouldn't change anything at all. I had to amend the `run_hooks` macro to render hooks, as they previously relied on statement blocks to be rendered. While I was in there, I added a check to skip queries for empty hooks, which should fix #1108.

We should think hard about if there are any other built-in parts of the dbt codebase which rely on statements re-rendering queries - I don't believe there are, but if they do exist, they're probably not explicitly tested. We should also add a note to the release notes / migration guide describing this change in behavior, as it could be _very_ breaking for some dbt projects out there.

### CODE REVIEW

**Comment by drewbanin** [comment]
Turns out that this is how hooks work...

File: core/dbt/include/global_project/macros/materializations/helpers.sql [hunk 1]
```diff
@@ -5,9 +5,12 @@
         commit;
       {% endcall %}
     {% endif %}
-    {% call statement(auto_begin=inside_transaction) %}
-      {{ hook.get('sql') }}
-    {% endcall %}
+    {% set rendered = render(hook.get('sql')) | trim %}
+    {% if (rendered | length) > 0 %}
+      {% call statement(auto_begin=inside_transaction) %}
+        {{ render(hook.get('sql')) }}
```
Comment (beckjake) [inline core/dbt/include/global_project/macros/materializations/helpers.sql]: Why not just `{{ rendered }}` here?

Comment (drewbanin) [reply core/dbt/include/global_project/macros/materializations/helpers.sql]: because i forgot! Updating now

**Comment by drewbanin** [comment]
I actually feel _great_ about this hooks change. Hooks were previously kind of magic - I didn't realize that they only worked because they went through statements! I feel really good about making that particular interaction explicit, rather than implicit.

Super glad we're fixing this - just saw a similar (unrelated to hooks) issue pop up in Slack. Looks like there's a nonzero incidence of folks using code like:
```
{{ config(target_schema='{{ some jinja here }}') }}
```

which fails is terrible and confusing ways!

**Comment by blisteringherb** [comment]
@drewbanin If we're trying to use the` {{ config(target_schema='{{ env_var('SOME_ENV_VAR') }}') }}` syntax, what's the proper way to use that? I'm running into errors with every permutation I can think of.

**Comment by drewbanin** [comment]
@blisteringherb that would be
```
{{ config(target_schema=env_var('SOME_ENV_VAR')) }}
```

You generally don't want to "nest" curly brackets the way you've shown in your example.

**Comment by blisteringherb** [comment]
Thank you for your help! @drewbanin
