### PR TITLE
Expose the cache in dbt's rendering contexts (#1683)

### LINKED ISSUE #1683: Difference between behaviour of `already_exists` and `get_relation`
### Describe the bug
I am upgrading DBT from 0.12.2 to 0.14
Based on this [link](https://docs.getdbt.com/docs/adapter#section-already_exists), 
`already_exists` is deprecated and will be removed in favour of `get_relation`.

But I am seeing different behaviour of `get_relation`. 
I am using this macro, and this runs at the start and end of table creation.
```jinja
{% if not adapter.get_relation(target.dbname, this.schema, this.table)%}
    -- currently writing -1 to denote, macro has not run
    {{return(-1)}}
  {% else %}
    -- run count rows query
    {% call statement('rows_count_action', fetch_result=True) %}
        SELECT
            COUNT(*) AS rows_count
        FROM
            {{this}}
        {% if where_filter %}
        -- where filter only if where clause is present
        WHERE
            {{where_filter}}
        {% endif %}
    {% endcall %}
```

After table is created successfully in run and when I am running `get_relation` in a post-hook by above macro, it is giving me `none` value.

And when I run this in pre-hook, DBT is executing the else part even if the table does not exist and it throws an error relation does not exist in SELECT query.

### Steps To Reproduce
Models I am seeing this are custom materialized, which is based on `table` materialization. This problem is not happening in `table` materialization.

here is the code for the same.
```
{% materialization pm_transient, default %}
    {# table identifiers #}
    {%- set identifier = model['alias'] -%}
    {%- set tmp_source_suffix = '__dbt_source_tmp' -%}
    {%- set tmp_processed_suffix = '__dbt_incremental_tmp_' -%}

    {%- set target_relation = api.Relation.create(database=database, identifier=identifier, schema=schema, type='table') -%}
    {%- set tmp_source_relation = make_temp_relation(target_relation, tmp_source_suffix) -%}
    {%- set tmp_processed_relation = make_temp_relation(target_relation, tmp_processed_suffix) -%}

    -- drop the relations if they exists for some reason
    {{ adapter.drop_relation(target_relation) }}
    {{ adapter.drop_relation(tmp_source_relation) }}
    {{ adapter.drop_relation(tmp_processed_relation) }}

    {{ run_hooks(pre_hooks, inside_transaction=False) }}

    -- `BEGIN` happens here:
    {{ run_hooks(pre_hooks, inside_transaction=True) }}

    {%- call statement('source_table_creation') -%}
        {# Directly creating table from SQL to support Spectrum #}
        {{ dbt.create_table_as(False, tmp_source_relation, sql) }}
    {%- endcall -%}

    {{ adapter.drop_relation(tmp_processed_relation) }}
    {{ adapter.rename_relation(tmp_source_relation, tmp_processed_relation) }}

    {% call statement('main') %}
        {% set processed_table_sql -%}
            SELECT
                *
            FROM
                {{ tmp_processed_relation }}
        {%- endset %}

        -- Prepare temp table from scd logic
        {{ dbt.create_table_as(False, target_relation, processed_table_sql) }}
    {% endcall %}

    {{ run_hooks(post_hooks, inside_transaction=True) }}

    -- `COMMIT` happens here
    {{ adapter.commit() }}

    {{ drop_relation_if_exists(tmp_processed_relation) }}

    {{ run_hooks(post_hooks, inside_transaction=False) }}
{%- endmaterialization %}

```

Create a model using the above materialization and run a macro mentioned above in the post as post-hook. If it gives `-1` in audit table or in log that means `get_relation` is not working.

### Expected behavior
This used to work previously with 0.12.2 giving correct presence of table in database. `get_relation` is expected to behave similar to `already_exists` as it is the replacement. 

### Screenshots and log output
This is my post hook in dbt_project.yml file
```yml
    post-hook:
      - "{{ logging.log_model_end_event() }}"
      - sql: >-
          INSERT INTO
              {{target.schema}}.dbt_audit
              VALUES (
                  'completed model deployment'
                  , GETDATE()
                  , '{{this.schema}}'
                  , '{{this.table}}'
                  , '{{run_started_at}}'
                  , '{{invocation_id}}'
                  , {{get_count()}}
                  , '{{var('run_type')}}'
              )
        transaction: False
```

You can see in the first line 10 rows were inserted, but in INSERT INTO query where `-1` comes from the macro mentioned above I am getting -1 which means table does not exist.
```
2019-08-14 16:02:35,451 (Thread-1): SQL status: INSERT 0 10 in 0.32 seconds
...
2019-08-14 16:02:38,548 (Thread-1): Using redshift connection "dim_api_version".
2019-08-14 16:02:38,548 (Thread-1): On dim_api_version: 
        commit;
      
2019-08-14 16:02:39,060 (Thread-1): SQL status: COMMIT in 0.51 seconds
2019-08-14 16:02:39,072 (Thread-1): Using redshift connection "dim_api_version".
2019-08-14 16:02:39,072 (Thread-1): On dim_api_version: 
      INSERT INTO
    analytics_dbt_test.dbt_audit
    VALUES (
        'completed model deployment'
        , GETDATE()
        , 'analytics_dbt_test'
        , 'dim_api_version'
        , '2019-08-14 10:32:00.717778+00:00'
        , '1234f41f-2a11-44d6-b265-9942bfc8b102'
        , -1
        , 'not_defined'
    )
```

### System information
**Which database are you using dbt with?**
- [x] redshift

**The output of `dbt --version`:**
```
installed version: 0.14.0
   latest version: 0.14.0

Up to date!
```

**The operating system you're using:**
macOS Mojave 10.14.5
**The output of `python --version`:**
Python 3.7.0

### PR DESCRIPTION
**Pull request by beckjake**
Fixes #1683 

Expose some cache manipulation methods to materializations and macros. As part of that I moved around where we do our cache changes in dbt itself. This is a breaking change - I've updated the changelog accordingly.

I also spent some time/energy getting mypy happy with this part of the code.

I'm not sure, but it's possible that we should be stubbing these out during parsing with `@available.parse_none` instead of just `@available`.

### CODE REVIEW

File: core/dbt/include/global_project/macros/adapters/common.sql [hunk 1]
```diff
@@ -65,6 +65,9 @@
 {% endmacro %}
 
 {% macro create_table_as(temporary, relation, sql) -%}
+  {%- if not temporary -%}
```
Comment (drewbanin) [inline core/dbt/include/global_project/macros/adapters/common.sql]: Imagine that there's a SQL logic error in sql returned by `create_table_as`  - this code will:
1. add the relation to the cache
2. not actually create the relation in a subsequent `statement`

When we originally implemented the relation cache, we intentionally added usage constraints for ourselves - this is not a general-purpose cache, and it doesn't need to exactly track the state of the database in every case. I think this is one such issue - we decided that if models fail to build, then their cache status may be incorrect, as dbt will skip dependent models.

Do you think we should instead leave it up to materializations to operate on the cache? That would let us defer cache mutation until _after_ the sql has run successfully, but it definitely opens up a lot of surface area for implementation bugs.

What do you think?

Comment (beckjake) [reply core/dbt/include/global_project/macros/adapters/common.sql]: Oh no, that's a good point, doing it in the macro itself isn't safe. Too bad it's not an adapter method like drop/rename are!

>Do you think we should instead leave it up to materializations to operate on the cache?

I guess we have to if we want to support any level of flexibility here. I really don't like how this makes for an easy bug-by-omission where you can just forget to do something and screw up the cache. That will cause bugs that will really stink to track down. Maybe we can make it add to the cache after running the materialization unless you explicitly opt out in your materialization definition?

Comment (drewbanin) [reply core/dbt/include/global_project/macros/adapters/common.sql]: Sure - I totally buy that. I think materializations will generally continue to map 1-to-1 with relations in the database, so I'm ok with making the 90% case hard to mess up.

Here's a kind of wacky though: what if materializations _returned_ the relations that they created. The cache management work can still happen in Python, and materialization maintainers would just need to return the list of relations that they've created. We don't necessarily need to do that in this PR, but curious what you think

Comment (beckjake) [reply core/dbt/include/global_project/macros/adapters/common.sql]: Interesting! The downside is that means we break existing materializations, but if you're willing to do that, I'd prefer it.

If you're not, I just was playing with a proof of concept where you can add a `nocache` argument to your macro definition, like this:
```
{% materialization custom, default, nocache %}
...

-- here at the end I do an adapter.cache_added(relation) because I said I would
{% do adapter.cache_added(target_relation) %}
[% endmaterialization %}
```

And then `nocache` gets attached to the parsed materialization, parsing looks at it and returns a special kind of `ParsedMacro` that indicates it should not be cached, and then the node runner decides not to cache it after running. It feels messy.

Comment (drewbanin) [reply core/dbt/include/global_project/macros/adapters/common.sql]: Yeah - I'd rather not throw things like this into the materialization tag if we don't have to.

I'm unsure what the right mechanism for "returning" is -- is it the `return()` function? Or something like `set_created_relations([...])`? Depending on how we implement this, we can determine if these relations are _not_ returned, and then do something sane with the cache by default (possibly with a deprecation warning...)

Comment (beckjake) [reply core/dbt/include/global_project/macros/adapters/common.sql]: I think the `return` function. If there's no result (because nobody called `return()`) it will be a string, so we can detect if it's a string and do the default drop.

Comment (drewbanin) [reply core/dbt/include/global_project/macros/adapters/common.sql]: word - i was worried about the stringy default response, but that really shouldn't be an issue. I'd be ok with proceeding with this approach in this PR if you think we're ready to implement it now.

Can we return something like `{"relations": [...]}`. I have some thoughts about other info we'd want to return in the future, and it would be good to give our future selves some options :D
